In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('C:/Users/j/squares2.jpg')

In [3]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [4]:
corners = cv2.goodFeaturesToTrack(img_gray, 500, 0.1, 100) 
#100 = max corners, 0.01 = corner quality to be detected, 10 = minimum distance between each corner

In [5]:
corners = np.int0(corners)

C:\Users\j\AppData\Local\Temp\ipykernel_4616\929114271.py:1: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  corners = np.int0(corners)


In [6]:
for corner in corners:
    x, y = corner.ravel()
    cv2.circle(img, (x, y), 5, (0, 0, 255), -1)
    #3 = edges pixel, -1 = thickness

In [43]:
print(corners)

[[[ 232. 1105.]]

 [[  66. 1342.]]

 [[  58. 1543.]]

 [[  91.  767.]]

 [[ 244.  721.]]

 [[  83.  954.]]

 [[ 221. 1509.]]

 [[  41. 1963.]]

 [[ 383. 1689.]]

 [[ 568.  620.]]

 [[ 213. 1720.]]

 [[ 391. 1266.]]

 [[ 403.  671.]]

 [[ 226. 1305.]]

 [[ 983. 1096.]]

 [[  51. 1750.]]

 [[ 400.  864.]]

 [[ 395. 1063.]]

 [[1085.  775.]]

 [[ 973.  708.]]

 [[ 970.  523.]]

 [[ 207. 1937.]]

 [[ 993. 1711.]]

 [[ 407.  483.]]

 [[1067.   76.]]

 [[1345.  141.]]

 [[ 255.  355.]]

 [[ 238.  910.]]

 [[ 388. 1474.]]

 [[1281.  724.]]

 [[ 867. 1451.]]

 [[ 562. 1226.]]

 [[1324. 1829.]]

 [[ 570.  428.]]

 [[ 260.  179.]]

 [[1227. 1999.]]

 [[ 565. 1018.]]

 [[ 410.  300.]]

 [[ 113.  234.]]

 [[1098. 1347.]]

 [[1165.  151.]]

 [[ 566.  816.]]

 [[ 560. 1655.]]

 [[1176.  486.]]

 [[1414. 1673.]]

 [[ 967.  343.]]

 [[1109. 1752.]]

 [[ 997. 1929.]]

 [[1267.  388.]]

 [[ 573.   61.]]

 [[1194. 1018.]]

 [[1286.  896.]]

 [[1187.  836.]]

 [[1316. 1634.]]

 [[  75. 1145.]]

 [[1365.  

In [47]:
len(corners)

129

In [1]:
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'cv2' is not defined

REAL TIME CORNER DETECTION

In [6]:
cap = cv2.VideoCapture(0)

#to create trackbar
def nothing(x): #done for memory purposes. If there's no value changing on the trackbar it's poing to pass
    pass


cv2.namedWindow("Frame")
cv2.createTrackbar("quality", "Frame", 1, 100, nothing)

while True:
    _, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    quality = cv2.getTrackbarPos("quality", "Frame") #To get the value of the trackbar in real time
    quality = quality/100 if quality > 0 else 0.01
    corners = cv2.goodFeaturesToTrack(gray, 100, quality, 20)
    
    if corners is not None:
        corners = np.int0(corners)
        
        for corner in corners:
            x, y = corner.ravel()
            cv2.circle(frame, (x, y), 3, (0, 0, 255), -1)
    
    cv2.imshow("Frame", frame)
    
    key = cv2.waitKey(1)
    if key==27:
        break
        
cap.release()
cv2.destroyAllWindows()

C:\Users\j\AppData\Local\Temp\ipykernel_6172\3708692634.py:20: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  corners = np.int0(corners)
